version: "3.8"

services:
  frontend:
    container_name: nextjs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 3000:3000
    restart: always
    networks:
      - my_network

  backend:
    container_name: nestjs
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 3001:3001
    restart: always
    networks:
      - my_network


networks:
  my_network:
